// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emzcdxpagwnxesvnsfje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtemNkeHBhZ3dueGVzdm5zZmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDI1MzMsImV4cCI6MjA2NDcxODUzM30._bio527GlUa910ZGaUjiCLmkli8dgE67p9A7TxO0ui0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

